// <auto-generated />
using System;
using DominosDriverHustleComp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DominosDriverHustleComp.Server.Migrations
{
    [DbContext(typeof(HustleCompContext))]
    partial class HustleCompContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("DominosDriverHustleComp.Server.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AvgHustleIn")
                        .HasColumnType("REAL");

                    b.Property<float>("AvgHustleOut")
                        .HasColumnType("REAL");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DominosDriverHustleComp.Server.Models.DeliverySummary", b =>
                {
                    b.Property<DateTime>("WeekEnding")
                        .HasColumnType("TEXT");

                    b.Property<float>("AvgHustleCombined")
                        .HasColumnType("REAL");

                    b.Property<float>("AvgHustleIn")
                        .HasColumnType("REAL");

                    b.Property<float>("AvgHustleOut")
                        .HasColumnType("REAL");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("WeekEnding");

                    b.HasIndex("DriverId");

                    b.ToTable("DeliverySummaries");
                });

            modelBuilder.Entity("DominosDriverHustleComp.Server.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DominosDriverHustleComp.Server.Models.WeeklySummary", b =>
                {
                    b.Property<DateTime>("WeekEnding")
                        .HasColumnType("TEXT");

                    b.Property<float>("AvgHustleCombined")
                        .HasColumnType("REAL");

                    b.Property<float>("AvgHustleIn")
                        .HasColumnType("REAL");

                    b.Property<float>("AvgHustleOut")
                        .HasColumnType("REAL");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("WeekEnding");

                    b.ToTable("WeeklySummaries");
                });

            modelBuilder.Entity("DominosDriverHustleComp.Server.Models.Delivery", b =>
                {
                    b.HasOne("DominosDriverHustleComp.Server.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DominosDriverHustleComp.Server.Models.DeliverySummary", b =>
                {
                    b.HasOne("DominosDriverHustleComp.Server.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
